apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: frontend-mongo-pacman
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/ysubrama-tenant/mongo-pacman/frontend-mongo-pacman@sha256:3b6bcb352fa11c03df928de67b6bd3ac22afb06caadccf39925c2ac21c103994
        name: container-image
        resources: {}
status: {}
