apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: frontend-mongo-pacman
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: frontend-mongo-pacman
    app.kubernetes.io/part-of: mongo-pacman
  name: frontend-mongo-pacman
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: frontend-mongo-pacman
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: frontend-mongo-pacman
    spec:
      containers:
      - env:
        - name: MONGO_SERVICE_HOST
          value: mongodb
        image: quay.io/redhat-user-workloads-stage/ysubrama-tenant/mongo-pacman/frontend-mongo-pacman@sha256:3b6bcb352fa11c03df928de67b6bd3ac22afb06caadccf39925c2ac21c103994
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
